layout_spectrum: 0.8470993
color:
  saturation: 0.5192533
  lightness: 0.6943396
  brandStrength: 0.8423971
  brandColors:
    - '#05020E'
    - '#E9CFB4'
    - '#F34363'
    - '#775C42'
    - '#202E5C'
  rhythmicContrast: 0.6515618
typography_spectrum: 0.142332
name: The Reel Makeup Artist
