favicon: null
name: The Reel Makeup Artist
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5192533
  brandStrength: 0.7824919
  rhythmicContrast: 0.75
  brandColors:
    - '#05020E'
    - '#E9CFB4'
    - '#F34363'
    - '#775C42'
    - '#202E5C'
  lightness: 0.6943396
typography_spectrum: 0.9232008
layout_spectrum: 0.6353384
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
